@baseurl = http://localhost:3003

### GET endpoint /
GET {{baseurl}}/api/blogs

### GET endpoint /api/
GET {{baseurl}}/api/users

### POST endpoint /api/users
POST {{baseurl}}/api/users
Content-Type: application/json

{
    "username":"Tinkh",
    "name":"hehehe",
    "password":"Tintin"
}
### Login 
POST {{baseurl}}/api/login
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5c2VybmFtZSI6Im1sdXVra2FpIiwiaW

{
    "username":"Tinkh",
    "password":"Tintin"
}
### POST endpoint /api/blogs after login
POST {{baseurl}}/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRpbmtoIiwiaWQiOiI2NTRiZTc1NTUwNzQyY2RiNGI4M2ZlNDIiLCJpYXQiOjE2OTk0NzY2NzksImV4cCI6MTY5OTQ4MDI3OX0.-q8GsLkp1WyuldjRjd5hFlJX5-ohaXoA5nH2I0LELqE

{    "title": "Example Blog Post",
    "author": "John Doe",
    "url": "https://example.com/blogpost",
    "likes": 230802,
    "user": "654be75550742cdb4b83fe42"
}

### Delete
DELETE {{baseurl}}/api/blogs/654bf50123c9efbd8a5d7c87
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRpbmtoIiwiaWQiOiI2NTRiZTc1NTUwNzQyY2RiNGI4M2ZlNDIiLCJpYXQiOjE2OTk0NzM2ODYsImV4cCI6MTY5OTQ3NzI4Nn0.FkmVfTObiuucWXgd6eT4ti3st_fuvVEHPt8z8RzjoRk

