@baseurl = http://localhost:3003

### GET endpoint /
GET {{baseurl}}/api/blogs

### GET endpoint /api/
GET {{baseurl}}/api/users

### POST endpoint /api/users
POST {{baseurl}}/api/users
Content-Type: application/json

{
    "username":"Tink",
    "name":"hehehe",
    "password":"Tintin"
}

### POST endpoint /api/blogs
POST {{baseurl}}/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRpbmtodTEyMzQiLCJpZCI6IjY1NGEzOTQ4ZTViYzFhZDg0Y2IwNDVhMiIsImlhdCI6MTY5OTM2MzE2NywiZXhwIjoxNjk5MzY2NzY3fQ.bLozXkJTYgssA_o4M0b9e2s5OdmgKwZTfCiLtztpjtE

{
    "title": "Example Blog Post",
    "author": "John Doe",
    "url": "https://example.com/blogpost",
    "likes": 2308,
    "user": "65436ec1fe2121fc71cf17a6" 
}

###
POST {{baseurl}}/api/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5c2VybmFtZSI6Im1sdXVra2FpIiwiaW

{
    "username":"Tinkhu1234",
    "password":"113"
}